FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apt update
RUN apt install -y unzip
#run apt-get install -y linux-perf # move to top

WORKDIR /app

RUN mkdir -p /app/perf-reporting/data


COPY perf-reporting/perf-report.sh /app/perf-reporting/perf-report.sh
